### ISSUE TITLE
Spring-Boot: NoSuchMethodError - RepositoryRestMvcConfiguration.entityLinks()

### ISSUE THREAD

**Issue by sddakoty** [la-team/light-admin#172]
I try to run https://github.com/la-team/lightadmin-springboot with spring-boot-starter-parent 1.2.1.RELEASE and lightadmin.version=1.1.0.BUILD-SNAPSHOT.

Result: NoSuchMethodError - RepositoryRestMvcConfiguration.entityLinks()
Which is strange because the lightadmin snapshot clearly has this method, and is also on classpath. What might be wrong here?
```
[ERROR] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] - Servlet [lightadmin-dispatcher] in web application [] threw load() exception
java.lang.NoSuchMethodError: org.springframework.data.rest.webmvc.config.RepositoryRestMvcConfiguration.entityLinks()Lorg/springframework/hateoas/EntityLinks;
	at org.lightadmin.core.config.context.LightAdminRepositoryRestMvcConfiguration.entityLinks(LightAdminRepositoryRestMvcConfiguration.java:68) ~[lightadmin-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
	at org.lightadmin.core.config.context.LightAdminRepositoryRestMvcConfiguration$$EnhancerBySpringCGLIB$$59177c69.CGLIB$entityLinks$3(<generated>) ~[spring-core-4.1.4.RELEASE.jar:1.1.0.BUILD-SNAPSHOT]
	at org.lightadmin.core.config.context.LightAdminRepositoryRestMvcConfiguration$$EnhancerBySpringCGLIB$$59177c69$$FastClassBySpringCGLIB$$1e1af318.invoke(<generated>) ~[spring-core-4.1.4.RELEASE.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:309) ~[spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.lightadmin.core.config.context.LightAdminRepositoryRestMvcConfiguration$$EnhancerBySpringCGLIB$$59177c69.entityLinks(<generated>) ~[spring-core-4.1.4.RELEASE.jar:1.1.0.BUILD-SNAPSHOT]
	at org.lightadmin.core.config.context.LightAdminRepositoryRestMvcConfiguration.entityLinks(LightAdminRepositoryRestMvcConfiguration.java:53) ~[lightadmin-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
	at org.lightadmin.core.config.context.LightAdminRepositoryRestMvcConfiguration$$EnhancerBySpringCGLIB$$59177c69.CGLIB$entityLinks$2(<generated>) ~[spring-core-4.1.4.RELEASE.jar:1.1.0.BUILD-SNAPSHOT]
	at org.lightadmin.core.config.context.LightAdminRepositoryRestMvcConfiguration$$EnhancerBySpringCGLIB$$59177c69$$FastClassBySpringCGLIB$$1e1af318.invoke(<generated>) ~[spring-core-4.1.4.RELEASE.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:309) ~[spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.lightadmin.core.config.context.LightAdminRepositoryRestMvcConfiguration$$EnhancerBySpringCGLIB$$59177c69.entityLinks(<generated>) ~[spring-core-4.1.4.RELEASE.jar:1.1.0.BUILD-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_51]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_51]
```

**Comment by sddakoty** [comment]
Sorry I had the tomcat server lib as dependency explicit. When I removed it from the eclipse config it worked, as expected.

**Comment by lrkwz** [comment]
I still have the same problem using 

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.2.2.RELEASE</version>
    </parent>

no luck even with

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        
        
        <lightadmin.version>1.1.0.BUILD-SNAPSHOT</lightadmin.version>
        <springloaded.version>1.2.0.RELEASE</springloaded.version>
    </properties>

**Comment by sddakoty** [comment]
Check if you have the tomcat dependency configured in your eclipse/IDE project.

**Comment by lrkwz** [comment]
Same if 

      mvn spring-boot:run

**Comment by magno32** [comment]
I see the same issue.

Spring Boot 1.2.2
Maven
Netbeans

I don't understand how changing the tomcat dependency affects this, as the Spring Starter project already had it as a maven dependency, scope provided since it is generated as a WAR for deployment.

Any pointers there?

**Comment by lazaridis-com** [comment]
(similar issue: la-team/lightadmin-springboot:5 )

@sddakoty , I have the same problem, as @lrkwz  with `mvn spring-boot:run`

Can you please reopen this issue, so it's on the radar again?

**Comment by sddakoty** [comment]
Reopened as many users have the same problem.

**Comment by lazaridis-com** [comment]
@lrkwz , @magno32 , try with latest master (13f255a), should work now (with spring-boot-1.2.3)

**Comment by javaguy44** [comment]
Hi, I have the same problem as everyone else using https://github.com/la-team/lightadmin-springboot when I run as LightAdminBootApplication main or mvn spring-boot:run

I've tried latest master as @lazaridis-com posted and all is working.

**Comment by lrkwz** [comment]
yep 13f255a works with spring-boot v. 1.2.3-RELEASE like a charm.
Thnks @lazaridis-com.

**Comment by lazaridis-com** [comment]
@javaguy44 @lrkwz , very nice. There is a negative report on #198, can you confirm / deny ?

**Comment by jimmyfm** [comment]
@lrkwz Italians! Italians everywhere!

**Comment by lazaridis-com** [comment]
@jimmyfm , btw., hows "una fatsa unna ratsa" correctly written?

**Comment by lrkwz** [comment]
@lazaridis-com ["Una faccia una razza"](http://en.wikipedia.org/wiki/Greece%E2%80%93Italy_relations#Una_faccia_una_razza)

**Comment by lazaridis-com** [comment]
@sddakoty , you can close this now.

@lrkwz , @jimmyfm , @javaguy44 , @magno32 - please note that I continue work on my repo, as the inactive project-owner here introduces too much barriers and delays (see #197). I need some people to run the tests, as the test-system does not work at all on my side. Just checkout code from https://github.com/lazaridis-com/light-admin, do a `mvn clean install`, which should make the version available on your local repo. as for testing, see the readme, or await further issues within my repo.

**Comment by dsteinkopf** [comment]
commit 56bd1c104a6 from https://github.com/lazaridis-com/light-admin finally works for me with springboot 1.2.3.
Thank you.

**Comment by dsteinkopf** [comment]
As said in #211: In my spring boot application everything seems to work fine with currrent lightadmin-1.2.0.BUILD-SNAPSHOT from lightadmin-nexus-snapshots (see lightadmin-springboot example). Thank you again.

**Comment by max-dev** [comment]
You're welcome and sorry for such a big delay.
