### ISSUE TITLE
Websphere Server 8.5: enumeration doesn't work

### ISSUE THREAD

**Issue by enriquejc1979** [la-team/light-admin#191]
I'm using  an enumeration type in the method "formView" of my AdministrationConfiguration. The enumeration type (org.lightadmin.api.config.utils.EnumElement[]) works correctly for my local Tomcat Server 7 but doesn't work for the integration Websphere Server 8.5. A java.lang.StackOverflowError is happening (attached below the trace).

Caused by: org.apache.tiles.util.TilesIOException: JSPException including path '/views/pages/create.jsp'.
	at org.apache.tiles.servlet.context.ServletUtil.wrapServletException(ServletUtil.java:241)
	at org.apache.tiles.jsp.context.JspTilesRequestContext.include(JspTilesRequestContext.java:105)
	at org.apache.tiles.jsp.context.JspTilesRequestContext.dispatch(JspTilesRequestContext.java:96)
	at org.apache.tiles.renderer.impl.TemplateAttributeRenderer.write(TemplateAttributeRenderer.java:44)
	at org.apache.tiles.renderer.impl.AbstractBaseAttributeRenderer.render(AbstractBaseAttributeRenderer.java:106)
	at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:670)
	at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:690)
	... 84 more
Caused by: java.lang.StackOverflowError
	at org.lightadmin.core.view.editor.JspFragmentFieldControl.doTag(JspFragmentFieldControl.java:47)
	at org.lightadmin.core.view.tags.form.EditControlDispatcherTag.doTag(EditControlDispatcherTag.java:54)
	at com.ibm.ws.jsp.tagfile.lightadmin_2D_1_2E_1_2E_0_2E_BUILD_2D_SNAPSHOT._edit_2D_control._jspx_meth_light_edit$1control$1dispatcher_0(_edit_2D_control.java:371)
	at com.ibm.ws.jsp.tagfile.lightadmin_2D_1_2E_1_2E_0_2E_BUILD_2D_SNAPSHOT._edit_2D_control.doTag(_edit_2D_control.java:133)
	at com.ibm._jsp._create._jspx_meth_light$1jsp_edit$1control_0(_create.java:600)
	at com.ibm._jsp._create._jspx_meth_c_if_1(_create.java:632)
	at com.ibm._jsp._create._jspx_meth_c_forEach_0(_create.java:671)
	at com.ibm._jsp._create._jspService(_create.java:215)
	at com.ibm.ws.jsp.runtime.HttpJspBase.service(HttpJspBase.java:99)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:779)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:478)
	at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:178)
	at com.ibm.wsspi.webcontainer.servlet.GenericServletWrapper.handleRequest(GenericServletWrapper.java:122)
	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper.handleRequest(AbstractJSPExtensionServletWrapper.java:220)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:136)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:79)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:967)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1107)
	at com.ibm.ws.webcontainer.webapp.WebAppRequestDispatcher.dispatch(WebAppRequestDispatcher.java:1385)
	at com.ibm.ws.webcontainer.webapp.WebAppRequestDispatcher.include(WebAppRequestDispatcher.java:549)
	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:1045)
	at org.apache.jasper.runtime.PageContextImpl.include(PageContextImpl.java:537)
	at org.apache.tiles.jsp.context.JspTilesRequestContext.include(JspTilesRequestContext.java:103)
	... 89 more

**Comment by lazaridis-com** [comment]
@enriquejc1979  , can you see to run the tests mentioned in #202?
